### ISSUE TITLE
Keyboard shortcut for inline code

### ISSUE THREAD

**Issue by khanlou** [nothingmagical/whiskey-issues#104]
I write a lot of code for my blog, so I'm used to being able to wrap a highlighted segment in backticks with a keyboard shortcut. Other apps I've seen use ⌘K, although I know that's being used for links right now.

(Great app!)

**Comment by soffes** [comment]
Love this.

**Comment by soffes** [comment]
Went with ⌘D. Don't love that but anything related to C or O is definitely taken. K is used for links in lots of places on OS X. If you have another letter you prefer, I'd love to hear why :)
