### ISSUE TITLE
Wrap links inline instead of presenting a sheet

### ISSUE THREAD

**Issue by khanlou** [nothingmagical/whiskey-issues#105]
When I hit ⌘K to add a link, Whiskey slides down a sheet to ask for the URL I'd like the link to point to. It would be better if the app just wrapped my selection in brackets, appended the parentheses after the brackets, and placed my cursor in between the parentheses. That way, I don't even have to hit enter when I paste the link in. Also, if I'm not ready to place the link yet, I can just have an empty placeholder to remind me that I want to put a link there, and it doesn't interrupt my writing.

I've seen other apps go so far as to put whatever's on your clipboard inside the parens (assuming it's a link), but I think that's taking it a bit too far.

**Comment by soffes** [comment]
Ya that's better. Good call.

**Comment by soffes** [comment]
What should it do if there's not selection?

**Comment by soffes** [comment]
Nevermind. I have a thing for that :)
