### ISSUE TITLE
Remember window size/position after restarting Whiskey

### ISSUE THREAD

**Issue by apacala** [nothingmagical/whiskey-issues#47]
Currently when I edit a file in Whiskey it opens in a small window in the bottom left corner of my screen. It would be nice if the app remembered the last used edtior window size/position.

**Comment by pslobo** [comment]
I'm experiencing this too, quite annoying in fact. Irrespective of which screen Whiskey was last opened on or at which size the window was, it'll always open as a small square near the bottom left corner of the main screen.

**Comment by soffes** [comment]
Ya annoying. This bugs me too. Have a lot to do before I send out a new build due to some major internal changes to make stuff like lists possible. Hopefully this will be out soon after that release comes out.

**Comment by apacala** [comment]
Thanks :heart:
