### ISSUE TITLE
Code duplicated in HTML

### ISSUE THREAD

**Issue by soffes** [nothingmagical/whiskey-issues#55]
![screen shot 2014-12-21 at 9 43 04 pm](https://cloud.githubusercontent.com/assets/52870/5538330/5e94a818-8a77-11e4-870f-5c3e69437dbc.png)

**Comment by andrewcopp** [comment]
I just brought the same problem to your attention on Twitter. You asked me to report it so I will include my screenshot.

![screenshot 2015-06-01 17 41 18](https://cloud.githubusercontent.com/assets/1331900/7925074/e9bdea40-088e-11e5-91f0-99324192f204.png)
