### ISSUE TITLE
Code Colouring isn't working properly with dark themes

### ISSUE THREAD

**Issue by pslobo** [nothingmagical/whiskey-issues#62]
Code colouring isn’t working properly in the darker themes. It’ll change the background colour to the light theme
![screen shot 2015-01-13 at 16 08 04](https://cloud.githubusercontent.com/assets/1452095/5723756/62240dde-9b3e-11e4-8659-885e831b0bbe.png)

**Comment by soffes** [comment]
Fixed in nothingmagical/whiskey@ae580cc8d96f284a0478532b60929f19de358797
