### ISSUE TITLE
Quick look plugin

### ISSUE THREAD

**Issue by kylef** [nothingmagical/whiskey-issues#65]
Would be nice to preview the markdown document in Finder by having a quick look plugin using Whiskey.

![screen shot 2015-01-15 at 15 28 04](https://cloud.githubusercontent.com/assets/44164/5759073/3b820486-9ccb-11e4-9e81-7aaaa7c4eb3a.png)

**Comment by soffes** [comment]
100%. Easy to do too!

**Comment by soffes** [comment]
Duplicate of #20.
