### ISSUE TITLE
Dragging files onto the Whiskey dock icon doesn't open them

### ISSUE THREAD

**Issue by kylef** [nothingmagical/whiskey-issues#67]
![screen recording 2015-01-16 at 01 37 pm](https://cloud.githubusercontent.com/assets/44164/5776231/db0f4504-9d84-11e4-96e8-33b65e9b2523.gif)

I'd expect doing the above would open the markdown document in Whiskey.

**Comment by soffes** [comment]
Good call.

**Comment by soffes** [comment]
This appears to be working in 0.3.8
