### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by kylef** [nothingmagical/whiskey-issues#70]
Would be nice to have a Whiskey document in full-screen.

**Comment by soffes** [comment]
You can open the window in full screen. What specifically are you looking for here?

**Comment by kylef** [comment]
Basically turning the green button into the full-screen button like Safari, where tapping it makes Safari take over the whole screen. I have an 11" MacBook Air and every little pixel counts!

![screen shot 2015-01-26 at 11 33 05](https://cloud.githubusercontent.com/assets/44164/5899120/1e9e2642-a54f-11e4-9529-7f0f882e794c.png)

See Apple's [Implementing the Full-Screen Experience](https://developer.apple.com/library/mac/documentation/General/Conceptual/MOSXAppProgrammingGuide/FullScreenApp/FullScreenApp.html) for implementation details.

**Comment by soffes** [comment]
Oh that used to work. My bad.

**Comment by bshakr** [comment]
+1 on this issue @soffes
