### ISSUE TITLE
Outline Preview Displays Markdown Characters

### ISSUE THREAD

**Issue by thebearjew** [nothingmagical/whiskey-issues#71]
#### Possible bug:

In the outline preview sidebar, markdown characters `_`, `*`, `**` are displayed. Not entirely sure if this is an intended feature, but I would assume as the heading characters `###` are selectively removed, these should be as well. 

![screen shot 2015-01-25 at 10 44 17 pm](https://cloud.githubusercontent.com/assets/5200812/5896089/d637c428-a4e3-11e4-92c7-3c7bf1a6f90d.png)

**Comment by soffes** [comment]
Oh do you have italics in your headers? I'm definitely not looking for that in the sidebar. Easy to add though.

**Comment by soffes** [comment]
Duplicate of #71
