### ISSUE TITLE
Whiskey Doesn't Open Files When Using "Open With"

### ISSUE THREAD

**Issue by thebearjew** [nothingmagical/whiskey-issues#72]
When using "open with" right-click option on a markdown file, Whiskey launches but does not open the file/a new file.

Just going to assume this feature has not been fully implemented yet/not working.

**Comment by soffes** [comment]
Ya. Thanks for reporting!

**Comment by DerBarenJude** [comment]
You got it. Happy to help I really like the design and I want to make Whiskey possible. Other markdown editors suck.

**Comment by DerBarenJude** [comment]
@soffes A little update to the inability to open files. I think it consistently happens with .md files which I've obtained from MacDown and Byword.
