### ISSUE TITLE
Outline should show page breaks

### ISSUE THREAD

**Issue by kylef** [nothingmagical/whiskey-issues#74]
I think it would make sense to show page breaks in the outline (`---`). It would be nice for using Whiskey with Deckset where the page breaks indicate separate slides.

![screen shot 2015-01-26 at 11 41 01](https://cloud.githubusercontent.com/assets/44164/5899226/364a6462-a550-11e4-999c-bcbe268cfb87.png)

**Comment by soffes** [comment]
Love this.
