### ISSUE TITLE
Renaming new .txt file to .markdown

### ISSUE THREAD

**Issue by CalebGrove** [nothingmagical/whiskey-issues#76]
When a new file is saved as a .txt from within Whiskey, then changes are made to the file and it is saved again, Whiskey renames the file to filename.markdown instead of maintaining the .txt extension. Here are the steps to replicate:

1. Open a new window in Whiskey. Type in `Test`.
2. ⌘S to save the file – save it to the desktop and name it `test.txt`. **Don't close the Whiskey window.**
3. Add some more text to the file which is still open in Whiskey.
4. ⌘S to save the file again. **The `test.txt` file will be renamed to `test.markdown`.**

**Comment by soffes** [comment]
Hah definitely a bug. I've been trying to force the default extension to `.markdown` (unsuccessfully) for awhile now. I bet this is a side effect. Thanks for reporting!

**Comment by DerBarenJude** [comment]
I would like to add that whiskey will not read/open any `.md` files for me. Occasionally it crashes.

Working on more data to reproduce the ill file a bug

**Comment by CalebGrove** [comment]
@DerBarenJude For me, it opens/reads `.md` files just fine. ¯\_(ツ)_/¯

**Comment by DerBarenJude** [comment]
Interesting, I'll keep tinkering. In general it's very spotty with opening so I guess that's non-specific to file types.
