### ISSUE TITLE
Print As PDF Formatting Issue

### ISSUE THREAD

**Issue by thebearjew** [nothingmagical/whiskey-issues#77]
There's an issue with the spacing between pages when printing a markdown file as a PDF.
There is almost half a page of excess spacing when attempting to print, ![seen here](https://cloud.githubusercontent.com/assets/5200812/5930101/fdac3982-a63f-11e4-90a6-7f19ed6e2d17.png).

This is not limited to lists, happens with any length, any style markdown document.

**Comment by soffes** [comment]
Printing needs a lot of work. I'm just using the automatic stuff and it's not great. Going to have to work on this for a bit.

**Comment by JacobRYoung** [comment]
Glad to hear.
Almost 6 months to the day >.,<

Glad to see you're back at it :smiley:
