### ISSUE TITLE
Can't type in textfield after launching

### ISSUE THREAD

**Issue by tspangler** [nothingmagical/whiskey-issues#81]
Whiskey opens to a new document, but I can’t type anything until I toggle the preview pane on. And then, the preview pane doesn’t actually appear until I toggle it again.

The attached screencast should show the behavior, as well the console error I receive when quitting.

https://www.dropbox.com/s/9txnashw1ovy4z9/WhiskeyBugReport.m4v?dl=0

**Comment by soffes** [comment]
Ya known issues with max widths for preview and outline. Thanks for reporting!

**Comment by soffes** [comment]
Duplicate of #99
