### ISSUE TITLE
Ghost Cursors

### ISSUE THREAD

**Issue by CalebGrove** [nothingmagical/whiskey-issues#83]
Here's a video of the problem: http://cl.ly/Zikx

How to duplicate (at least for me):

1. Open a file in Whiskey.
2. Move cursor via mouse or keyboard.

If the window looses focus, the cursor will begin to work properly once the window again gains focus. Also, note that the cursor is not blinking when it has this problem. When you begin typing, the problem solves itself.

**Comment by soffes** [comment]
Fixed in nothingmagical/whiskey@48a14b3ff638fd5a19cfaf24d1a5d27fd3a75166
