### ISSUE TITLE
Ruby code block causes Whiskey to not open markdown file

### ISSUE THREAD

**Issue by Darkle** [nothingmagical/whiskey-issues#90]
Whiskey wont open a markdown file if I have this code block in it: 
https://gist.github.com/Darkle/9fa1162ba9b44e8ed6a9

It seems to be line 12 that's causing the issue. If I remove it from the code block then Whiskey opens the markdown file just fine.

I'm running Whiskey version 0.3.7(49) on OSX 10.10.2

**Comment by soffes** [comment]
Fixed in nothingmagical/whiskey@ae580cc8d96f284a0478532b60929f19de358797
