### ISSUE TITLE
Exception when opening some markdown files on OS X 10.10.3

### ISSUE THREAD

**Issue by mbernson** [nothingmagical/whiskey-issues#91]
Hi Sam,

Whiskey seems to have trouble opening markdown files larger than (roughly) 10Kb on OS X 10.10.3. Smaller files are working fine for me.

I've posted the output from Console.app over here: https://gist.github.com/mbernson/7d07e2d8d1d8190c7bd8

Cheers, and thanks for creating this app. :)

**Comment by soffes** [comment]
It's unrelated to the size. It's a bug in my parser. Can you send me the document? sam@nothingmagical.com

**Comment by mbernson** [comment]
You're right, I've narrowed the issue down to some emphasized text inside a quote block. The following string of markdown will cause Whiskey 0.3.7 (49) to hang:

```
> I'm just *testing* here
```

The offending document (if you need it at all) is over here: https://git.syntaxleiden.nl/mathijs/samenvattingen/raw/0f6e5775c7115125e9e74a3f9039c56d6bc3130a/IITORG/Samenvatting.md
