### ISSUE TITLE
Can't Export

### ISSUE THREAD

**Issue by jgunson** [nothingmagical/whiskey-issues#94]
Hey,

Not sure if you're still supporting Whiskey, but been looking for something like this (and not Mou) for a while now. However, I keep having the same issue, which is preventing me from using it more often  - hope you can help.

Details below:

* Issue Description: For some reason I can't export to anything - whenever I try to all the options remain grayed out.
* Version: 0.3.7 (49)
* OS: Mac OSX 10.10.3

See screenshot below:

![screen shot 2015-05-20 at 12 32 24](https://cloud.githubusercontent.com/assets/6452514/7724750/6564145a-feec-11e4-82d3-c5ce565077a9.png)

**Comment by soffes** [comment]
Those aren't implemented yet. Definitely still working on it.

**Comment by jgunson** [comment]
Thanks for letting me know.

**Comment by soffes** [comment]
Closing for now since there are other issues tracking this feature.
