### ISSUE TITLE
Dots appear under text

### ISSUE THREAD

**Issue by roonieone** [nothingmagical/whiskey-issues#95]
Occasionally when writing text, several dots will appear under the text. Usually these dots will go away when selecting all of the text (+A) and deselecting it, though sometimes they do not go away without restarting the app.

![screen shot 2015-06-06 at 12 55 02 am](https://cloud.githubusercontent.com/assets/10133782/8018530/d6f03444-0be6-11e5-8d65-cc42d913695c.png)

**Comment by soffes** [comment]
Known issue. No idea why this is happening. Thanks for reporting!

**Comment by soffes** [comment]
Fixed in nothingmagical/whiskey@48a14b3ff638fd5a19cfaf24d1a5d27fd3a75166
