### ISSUE TITLE
Italic inside quotes goes crazy

### ISSUE THREAD

**Issue by alexito4** [nothingmagical/whiskey-issues#98]
if you write italic (or bold) inside a quote the app goes crazy. 

> some *quote*

when you write the ending * the character is not rendered and the window stops responding. If I open the document with some other editor I can see that the character is there. 

If I foce close and reopen Whiskey the app is still in an inconsistent state. I have to close and open other files to recover it.

![whiskey](https://cloud.githubusercontent.com/assets/750912/8397258/acb290d0-1dbd-11e5-8fce-a340c4529c40.gif)

Whiskey Version 0.3.7 (49)
OSX 10.10.3

*I hope the information helps ;)*

**Comment by soffes** [comment]
Just ran into this myself. Should be fixed in the next release



Sam

**Comment by soffes** [comment]
Disabled span parsing inside of block quotes in nothingmagical/whiskey@5f145a7091dd7f274de23c56c76b5a056299a692 since it doesn't work correctly anyway. This will be in 0.3.8
